import java.util.Scanner;

public class assignment1 {
    static void NumberGame() {
        Scanner sc = new Scanner(System.in);
        int randomNumber = 1 + (int) (100 * Math.random());
        int m = 3;
        int userNumber, i;
        System.out.println("---------------------------------------------------------------------------------");
        System.out.println("|Guess a number between 1 to 100 to match with the number generated by the system|");
        System.out.println("---------------------------------------------------------------------------------");
        for (i = 0; i < m; i++) {

            System.out.println("Enter your Guessed number" + "(trial:" + (i + 1) + ")");
            userNumber = sc.nextInt();

            if (userNumber == randomNumber) {
                System.out.println("Congratulations!! your number got matched :)");
            } else if (randomNumber < userNumber && i != m - 1) {
                System.out.println("Your number is " + (userNumber - randomNumber) + " lower than the system number");

            } else if (randomNumber > userNumber && i != m - 1) {
                System.out.println("Your number is " + (randomNumber - userNumber) + " higher than the system number");

            }

        }
        if (i == m) {
            System.out.println("==================================");
            System.out.println("|Oops!! you are out of this game | ");
            System.out.println("|***Only 3 trials were allowed***|");
            System.out.println("==================================");
            System.out.println("The number was " + randomNumber);
        }
    }

    public static void main(String args[]) {
        NumberGame();
    }

}
